version: '3'

services:
  auth:
    build:
      context: ../src/auth
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    command: node .
    depends_on:
      - database
  database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
